name: remote ssh command
on:
  push:
    branches:
      - "main"
      
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/github/project/todo-list-htmx
          git checkout main
          git pull
          go mod tidy
          go build -v -o app main.go
          cp ./app ~/application/app
          cd ~/application/
          chmod -x app
      
